#!/bin/bash
# VIGIL - Commandes Essentielles
# Script de référence rapide

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              VIGIL - COMMANDES ESSENTIELLES                  ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Couleurs
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📍 Répertoire actuel:${NC}"
echo "   $(pwd)"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🚀 INSTALLATION (une seule fois)${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "1. Créer l'environnement virtuel:"
echo "   python3 -m venv venv"
echo ""
echo "2. Activer l'environnement:"
echo "   source venv/bin/activate"
echo ""
echo "3. Installer les dépendances:"
echo "   pip install -r requirements.txt"
echo ""
echo "4. Configuration (optionnel):"
echo "   cp .env.example .env"
echo "   nano .env  # Ajouter vos clés API"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🧪 TESTS${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Option A${NC} - Test ultra-rapide (1 entreprise, 2 min):"
echo "   python quick_test.py"
echo ""
echo -e "${YELLOW}Option B${NC} - Test pilote complet (10 entreprises, 15 min):"
echo "   python test_pilot.py"
echo ""
echo -e "${YELLOW}Option C${NC} - Exemple basique:"
echo "   python main.py"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}📊 VOIR LES RÉSULTATS${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Test rapide:"
echo "   cat quick_test_report.json | jq '.summary'"
echo ""
echo "Test pilote:"
echo "   cat pilot_test_results/summary_*.json | jq '.'"
echo "   ls -lh pilot_test_results/"
echo ""
echo "Logs détaillés:"
echo "   tail -f vigil.log"
echo "   tail -f vigil_pilot_test.log"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}📚 DOCUMENTATION${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Guide de démarrage:"
echo "   cat GUIDE_DEMARRAGE.md"
echo ""
echo "README complet:"
echo "   cat README.md"
echo ""
echo "Cahier des charges:"
echo "   cat VIGIL_CDC.md"
echo ""
echo "Quick start:"
echo "   cat DEMARRAGE_RAPIDE.txt"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🔑 CLÉS API (optionnel pour le POC)${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Le code fonctionne en mode dégradé sans clés API."
echo "Pour des résultats complets:"
echo ""
echo "1. Crunchbase: https://www.crunchbase.com/api"
echo "2. Pappers:    https://www.pappers.fr/api"
echo ""
echo "Puis éditer .env:"
echo "   CRUNCHBASE_API_KEY=votre_cle"
echo "   PAPPERS_API_KEY=votre_cle"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🆘 DÉPANNAGE${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Module not found:"
echo "   pip install -r requirements.txt"
echo ""
echo "Vérifier l'environnement virtuel:"
echo "   which python  # doit pointer vers venv/"
echo ""
echo "Voir les logs d'erreur:"
echo "   tail -100 vigil.log"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ⚡ COMMANDE RECOMMANDÉE : python quick_test.py             ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
